package put.poznan.spring_vue.guest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import put.poznan.spring_vue.address.Address;
import put.poznan.spring_vue.room.Room;

import java.util.ArrayList;
import java.util.List;

@RestController // This means that this class is a Controller
@RequestMapping(path="/api/guest") // This means URL's start with /demo (after Application path)
public class GuestController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GuestRepository guestRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public ResponseEntity<Integer> addNewGuest (@RequestBody GuestDetails guestDetails) {
        try{
            Address address = guestRepository.findAddressByID(guestDetails.getAddressID());
            Guest _guest = new Guest(guestDetails.getFirstName(), guestDetails.getLastName(), guestDetails.getTelephone(), guestDetails.getDateOfBirth(), address);
            _guest = guestRepository.save(_guest);
            return new ResponseEntity<>(_guest.getId(), HttpStatus.CREATED);
        } catch (Exception e){
            e.printStackTrace();
            return new ResponseEntity<>(null, HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

    @GetMapping(path="/all")
    public @ResponseBody ResponseEntity<List<Guest>> getAllGuests() {
        try {
            List<Guest> guests = new ArrayList<Guest>(guestRepository.findAll());
            if (guests.isEmpty()) {
                return new ResponseEntity<>(HttpStatus.NO_CONTENT);
            }
            return new ResponseEntity<>(guests, HttpStatus.OK);
        } catch (Exception e) {
            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

}