package put.poznan.spring_vue.country;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

@RestController // This means that this class is a Controller
@RequestMapping(path="/api/country") // This means URL's start with /demo (after Application path)
public class CountryController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CountryRepository countryRepository;

//    @PostMapping(path="/add") // Map ONLY POST Requests
//    public ResponseEntity<Admin> addNewAdmin (@RequestBody Admin admin) {
//        try{
//            Admin _admin = adminRepository.save(admin);
//            return new ResponseEntity<>(_admin, HttpStatus.CREATED);
//        } catch (Exception e){
//            return new ResponseEntity<>(null, HttpStatus.INTERNAL_SERVER_ERROR);
//        }
//    }

    @GetMapping(path="/all")
    public @ResponseBody ResponseEntity<List<Country>> getAllCountries() {
        try {
            List<Country> countries = new ArrayList<Country>();
            countries.addAll(countryRepository.findAll());
            if (countries.isEmpty()) {
                return new ResponseEntity<>(HttpStatus.NO_CONTENT);
            }
            return new ResponseEntity<>(countries, HttpStatus.OK);
        } catch (Exception e) {
            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }
}