package put.poznan.spring_vue.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import put.poznan.spring_vue.AdminRepository;
import put.poznan.spring_vue.entities.Admin;
import put.poznan.spring_vue.services.AdminService;

@RestController // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AdminRepository adminRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public Admin addNewAdmin (@RequestBody Admin admin) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        /*** SAMPLE INPUT
        {
            "admin_id":1,
            "login":"logincurlnowy",
            "password":"haslocurlnowe",
            "firstName":"Jakub",
            "lastName":"Wrobel",
            "lastLogin":"2012-04-23T18:25:43.511Z"
        }
         ***/
        Admin dest = adminRepository.save(admin);
        return dest;
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Admin> getAllUsers() {
        // This returns a JSON or XML with the users
        return adminRepository.findAll();
    }
}